### ISSUE TITLE
Add non-interactive login

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tykctl#20]
### Current Behavior

There's only interactive option 

### Describe the solution you'd like

I want to do `./tykcli cloud login -u  {myusername} -p {my-pass} `

**Comment by yurisasuke** [comment]
This is already possible  use ./tykcli cloud login -e {email} -p {my-pass}

**Comment by letzya** [comment]
thanks. there's a typo here
`Example: tykctl cloud login --ba-pass=<use this only is staging> --ba-pass=<use this in staging>`
